# This file is generated by `jupyter-flex`, and ensures that voila
# can find our templates in editable installs

import voila.paths

templates_path = "@@@TEMPLATE_PATH@@@"

_voila_default_root_dirs = voila.paths._default_root_dirs


def _default_root_dirs():
    root_dirs = _voila_default_root_dirs()
    root_dirs.insert(0, templates_path)
    return root_dirs


voila.paths._default_root_dirs = _default_root_dirs
