# This file is generated by `jupyter-flex`, and ensures that voila
# can find our templates in editable installs

import os
import voila.paths as voila_paths
import textwrap


templates_path = "@@@TEMPLATE_PATH@@@"


def monkey_collect_template_paths(
    app_names, template_name='default', prune=False, root_dirs=None
):
    original = voila_paths.collect_paths(
        app_names,
        template_name,
        include_root_paths=True,
        prune=prune,
        root_dirs=root_dirs,
    )

    flex_voila_templates = os.path.join(
        templates_path, "voila", "templates"
    )
    flex_templates = [templates_path, flex_voila_templates]
    print(r"Jupyter Flex: patching template paths for editable install of "
            "jupyter-flex to include:")
    print(f"              {flex_voila_templates}")
    return flex_templates + original


def monkey_collect_static_paths(
    app_names, template_name='default', prune=False, root_dirs=None
):
    original = voila_paths.collect_paths(
        app_names,
        template_name,
        include_root_paths=False,
        prune=prune,
        root_dirs=root_dirs,
        subdir='static',
    )

    flex_nbconvert_templates = os.path.join(
        templates_path, "nbconvert", "templates"
    )
    flex_nbconvert_static = os.path.join(
        flex_nbconvert_templates, "flex", "static"
    )
    print(r"Jupyter Flex: patching static paths for editable install of "
            "jupyter-flex to include:")
    print(f"              {flex_nbconvert_templates}")
    print(f"              {flex_nbconvert_static}")

    flex_static_templates = [flex_nbconvert_templates, flex_nbconvert_static]

    return flex_static_templates + original


voila_paths.collect_template_paths = monkey_collect_template_paths
voila_paths.collect_static_paths = monkey_collect_static_paths
