name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.8.2
      options: --network-alias testhost

    services:
      selenium-hub:
        image: selenium/hub:3.141.59
        ports:
          - 4444:4444
        options: --health-cmd=/opt/bin/check-grid.sh --health-interval=15s --health-timeout=30s --health-retries=5

      chrome:
        image: selenium/node-chrome:3.141.59
        env:
          HUB_HOST: selenium-hub
          HUB_PORT: 4444
          SCREEN_WIDTH: 1440
          SCREEN_HEIGHT: 900

    env:
      SELENIUM_HUB_HOST: selenium-hub
      SELENIUM_HUB_PORT: 4444
      PYTEST_BASE_URL: http://testhost:8866

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U -r .github/workflows/requirements.txt
        pip freeze

    - name: Install package
      run: |
        pip install -e .
        pip freeze

    - name: Serve Voila
      run: |
        make serve-examples &

    - name: Verify Voila
      run: |
        curl http://localhost:8866/
        curl http://localhost:8866/voila/render/iris-clustering.ipynb

    - name: Make test
      run: |
        make test

    - name: Upload restuls
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: test-results
        path: test-results
