name: Test Package

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:3.141.59
        ports:
          - 4444:4444

      chrome:
        image: selenium/node-chrome:3.141.59
        env:
          HUB_HOST: selenium-hub
          HUB_PORT: 4444

    env:
      SELENIUM_HUB_HOST: selenium-hub
      TEST_HOST: testHost

    steps:
    - uses: actions/checkout@v2

    - name: Verify Connection
      env:
        PORT: ${{ job.services.selenium-hub.ports[4444] }}
      run: |
        ping -c 4 selenium-hub
        ping -c 4 localhost
