name: Test Package

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SELENIUM_HUB_HOST: selenium-hub
      TEST_HOST: testHost

    services:
      selenium-hub:
        image: selenium/hub:3.141.59-gold
      chrome:
        image: selenium/node-chrome:3.141.59-gold
        env:
          HUB_HOST: selenium-hub
          HUB_PORT: 4444
          SCREEN_WIDTH: 1440
          SCREEN_HEIGHT: 900

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U -r .github/workflows/requirements.txt
        pip freeze

    - name: Install package
      run: |
        pip install -e .
        pip freeze

    - name: Serve Voila
      run: |
        make serve-examples &

    # - name: Verify Connection
    #   env:
    #     PORT: ${{ job.services.selenium-hub.ports[4444] }}
    #   run: |
    #     ping -c 4 localhost
    #     ping -c 4 selenium-hub

    - name: Make test
      run: |
        PYTEST_BASE_URL=http://127.0.0.1:8866 make test

    - name: Upload restuls
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: test-results
        path: test-results
